# Generated by Django 3.0.10 on 2020-12-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeAPP', '0002_auto_20201215_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='DepartmentId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
