# Generated by Django 3.0.10 on 2020-12-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeAPP', '0003_auto_20201215_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='DepartmentId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
